<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <RootNamespace>Spt.Frontend</RootNamespace>
    <TargetFramework>net9.0-windows</TargetFramework>
    <LangVersion>latestmajor</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>wwwroot\app.ico</ApplicationIcon>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spt.Core\Spt.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**" />
    <EmbeddedResource Include="..\Common\bin\Release\net9.0\publish\**" />
    <EmbeddedResource Remove="..\Common\bin\Release\net9.0\publish\*.*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\_content\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="9.0.8"/>
  </ItemGroup>

</Project>
