<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <RootNamespace>Spt.Frontend</RootNamespace>
    <TargetFramework>net9.0-windows</TargetFramework>
    <LangVersion>latestmajor</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\*"/>
    <EmbeddedResource Include="Resources\*"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spt.Core\Spt.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\UserTabset.js" />
  </ItemGroup>

</Project>
