<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Spt.Backend</RootNamespace>
    <LangVersion>latestmajor</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Wpf" Version="9.0.40"/>
    <PackageReference Include="CodeBeam.MudBlazor.Extensions" Version="8.0.0" />
    <PackageReference Include="MudBlazor" Version="8.2.0"/>
    <PackageReference Include="MudBlazor.ThemeManager" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="zlib.net">
      <HintPath>.\SharedDependencies\zlib.net.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spt.Core\Spt.Core.csproj" />
  </ItemGroup>

</Project>
